---
title: "Intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Installing instaloader

Load library

```{r example}
library(instr)

```

Install instaloader and python: 

```{r, eval = F}
instr::install_instaloader()
```

```{r, eval=F}
instr::init_instr()
```

### Get Posts with Hashtag

Return a tibble with 10 Instagram posts that use `#coronavirus`.


```{r, eval = F}
covid <- insta_posts(query = "covid", 
                         scope = "hashtag",
                         max_posts = 3, 
                         scrape_comments = F)

head(covid)

```

### Get Posts from a Specific User

Return a tibble with the 5 Instagram posts by `francediplo`.

```{r, eval = F}
francediplo <- insta_posts(query = "francediplo", 
                         scope = "username",
                         max_posts = 3, 
                         scrape_comments = F)

francediplo
```

Return a tibble with the 5 Instagram posts by `francediplo`.

```{r, eval = F}
francediplo_comments <- insta_posts(query = "francediplo", 
                         scope = "username",
                         max_posts = 3, 
                         scrape_comments = T)

francediplo_comments
```
